/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "on-surface-variant": "#3c4a42",
        "on-secondary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#4edea3",
        "secondary": "#565e74",
        "primary-fixed": "#6ffbbe",
        "inverse-primary": "#4edea3",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#004395",
        "surface-tint": "#006c49",
        "background": "#f7f9fb",
        "on-primary-fixed": "#002113",
        "tertiary-fixed-dim": "#adc6ff",
        "on-background": "#191c1e",
        "on-tertiary-container": "#00367a",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-container": "#00422b",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-container": "#71a1ff",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#005236",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "tertiary": "#005ac2",
        "error-container": "#ffdad6",
        "secondary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#001a42",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary": "#006c49",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bbcabf",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "primary-container": "#10b981",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#5c647a",
        "outline": "#6c7a71",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "unit": "4px",
        "xl": "32px",
        "gutter": "24px",
        "container-max": "1280px",
        "sm": "8px",
        "2xl": "48px",
        "3xl": "64px",
        "xs": "4px",
        "md": "16px"
      },
      fontFamily: {
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400"}],
        "h3": ["20px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400"}],
        "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
